SET NAMES utf8mb4;
USE feiapi;

-- 土味情话表
CREATE TABLE IF NOT EXISTS `love_words`
(
    `id`    INT          NOT NULL AUTO_INCREMENT COMMENT '主键',
    `words` VARCHAR(512) NOT NULL COMMENT '土味情话内容',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='土味情话表';

-- 初始化 100 条土味情话
INSERT INTO `love_words` (`words`)
SELECT seed.words
FROM (
         SELECT '你知道你和星星有什么区别吗？星星在天上，你在我心里。' AS words
         UNION ALL SELECT '我想买一块地，什么地？你的死心塌地。'
         UNION ALL SELECT '你近视吗？不近视啊，那你怎么看不出我喜欢你。'
         UNION ALL SELECT '你属什么？我属于你。'
         UNION ALL SELECT '你知道我的缺点是什么吗？缺点你。'
         UNION ALL SELECT '你累不累？你都在我脑子里跑了一天了。'
         UNION ALL SELECT '你可以笑一下吗？我的咖啡忘记加糖了。'
         UNION ALL SELECT '你是可爱的男孩，我是可爱。'
         UNION ALL SELECT '你知道我的心在哪边吗？在你那边。'
         UNION ALL SELECT '你最近是不是胖了？因为你在我心里的分量变重了。'
         UNION ALL SELECT '我有超能力，超喜欢你。'
         UNION ALL SELECT '你是年少的欢喜，这句话反过来也是你。'
         UNION ALL SELECT '你闻到什么味道了吗？没有啊，怎么你一出来空气都是甜的。'
         UNION ALL SELECT '我怀疑你的本质是一本书，不然我怎么越看越想睡。'
         UNION ALL SELECT '我想你一定很忙，所以只看前三个字就好。'
         UNION ALL SELECT '你知道我为什么感冒了吗？因为我对你完全没有抵抗力。'
         UNION ALL SELECT '你有地图吗？我在你的眼睛里迷路了。'
         UNION ALL SELECT '我觉得你特别像一款游戏，我的世界。'
         UNION ALL SELECT '遇见你之后，我连风都是甜的。'
         UNION ALL SELECT '别人问我喜欢什么样的，我又要开始描述你了。'
         UNION ALL SELECT '你可以帮我洗个东西吗？喜欢我。'
         UNION ALL SELECT '你会喜欢我吗？不会的话，我教你。'
         UNION ALL SELECT '你今天怪怪的，怪好看的。'
         UNION ALL SELECT '我发现昨天很喜欢你，今天也很喜欢你，而且有预感明天也会喜欢你。'
         UNION ALL SELECT '我想变成风，这样就能一直围着你转。'
         UNION ALL SELECT '你是哪里人？你是我的心上人。'
         UNION ALL SELECT '我最近有点忙，忙什么？忙着喜欢你。'
         UNION ALL SELECT '你知道我最喜欢什么神吗？你的眼神。'
         UNION ALL SELECT '你为什么要害我？害我这么喜欢你。'
         UNION ALL SELECT '你是兔子吧？不然你怎么总是在我心里蹦蹦跳跳。'
         UNION ALL SELECT '你知道我最想喝什么吗？呵护你。'
         UNION ALL SELECT '你是不是偷东西了？不然你怎么偷走了我的心。'
         UNION ALL SELECT '我觉得你像一本书，因为越看越想翻到最后和你在一起。'
         UNION ALL SELECT '你是三，我是九，除了你还是你。'
         UNION ALL SELECT '你知道我的手为什么这么冷吗？因为还没牵到你。'
         UNION ALL SELECT '你可以借我一支笔吗？我想写下我们的故事。'
         UNION ALL SELECT '你是我绕过山河错落，才找到的人间烟火。'
         UNION ALL SELECT '你喜欢喝水吗？那你已经喜欢上百分之七十的我了。'
         UNION ALL SELECT '如果你前女友和现女友同时掉进水里，我可以做你女朋友吗？'
         UNION ALL SELECT '你是我电量只剩百分之一时，也想打开聊天框的人。'
         UNION ALL SELECT '我想吃碗面，什么面？你的心里面。'
         UNION ALL SELECT '你知道我和唐僧有什么区别吗？唐僧取经，我娶你。'
         UNION ALL SELECT '你是不是会弹吉他？不然你怎么拨动了我的心弦。'
         UNION ALL SELECT '你今天有点怪，哪里怪？怪让我心动的。'
         UNION ALL SELECT '我有两个心愿，你在身边，在你身边。'
         UNION ALL SELECT '你知道我最喜欢哪一天吗？有你的每一天。'
         UNION ALL SELECT '你是我始料不及的遇见，也是我突如其来的欢喜。'
         UNION ALL SELECT '我没有什么特别的本事，就是特别喜欢你。'
         UNION ALL SELECT '你是口中情，眼中喜，心中爱，意中人。'
         UNION ALL SELECT '我想去个地方，去哪里？去你心里。'
         UNION ALL SELECT '你知道我最珍惜什么吗？这句话的第一个字。'
         UNION ALL SELECT '你知道你像什么吗？像地球一样吸引着我。'
         UNION ALL SELECT '你会游泳吗？不会的话，那你可要小心了，因为你已经坠入爱河了。'
         UNION ALL SELECT '我可以向你问路吗？去哪里？去你心里。'
         UNION ALL SELECT '我想把世界上最好的都给你，却发现世界上最好的就是你。'
         UNION ALL SELECT '你的一句晚安，比满天星星都耀眼。'
         UNION ALL SELECT '你是我的今天，以及所有的明天。'
         UNION ALL SELECT '你知道我最喜欢什么季节吗？有你的季节。'
         UNION ALL SELECT '我觉得你特别像一首歌，百听不厌。'
         UNION ALL SELECT '你是方便面吗？不然我怎么会想泡你。'
         UNION ALL SELECT '你是云，我是海，想把你装进心怀。'
         UNION ALL SELECT '你像一颗糖，甜进了我的日常。'
         UNION ALL SELECT '今天的月亮不圆也没关系，反正我心里有你就够圆满。'
         UNION ALL SELECT '你是不是魔法师？不然你怎么让我的世界都变亮了。'
         UNION ALL SELECT '你知道我最怕什么吗？最怕失去你。'
         UNION ALL SELECT '我不想做你人生的插曲，我想做你余生的主题曲。'
         UNION ALL SELECT '你是我见过最可爱的算法，复杂又让我着迷。'
         UNION ALL SELECT '你出现之后，我的世界连空气都变得温柔。'
         UNION ALL SELECT '我本来要行走江湖的，看到你以后觉得江湖可以先停一停。'
         UNION ALL SELECT '你的名字明明很普通，却让我听一遍就心动。'
         UNION ALL SELECT '我这个人很简单，见山是山，见海是海，见你就是全世界。'
         UNION ALL SELECT '你是我平淡生活里最炽热的惊喜。'
         UNION ALL SELECT '想和你喝酒是假，想醉在你怀里是真。'
         UNION ALL SELECT '你知道我最擅长什么吗？最擅长喜欢你。'
         UNION ALL SELECT '我没什么出息，就想花你的钱，睡你的床，做你的老婆。'
         UNION ALL SELECT '你能不能闭嘴？我没有说话啊，可是我满脑子都是你的声音。'
         UNION ALL SELECT '我最近体重上升了，都怪你在我心里越来越重。'
         UNION ALL SELECT '你是我的可遇不可求，可遇不可留，可遇不可有。'
         UNION ALL SELECT '我想做你的鞋，这样就能陪你走完余生的路。'
         UNION ALL SELECT '你知道我为什么总是失眠吗？因为梦里都是你。'
         UNION ALL SELECT '你一笑起来，我的坏情绪就全部自动清零。'
         UNION ALL SELECT '你是我写了半截又舍不得结尾的情书。'
         UNION ALL SELECT '我想和你分享一切，清晨的阳光，夜晚的月亮，还有我全部的喜欢。'
         UNION ALL SELECT '你不用多好，我喜欢就好。我没有很好，你不嫌弃就好。'
         UNION ALL SELECT '你是我心里的一把火，点亮了所有沉默。'
         UNION ALL SELECT '你是例外，也是偏爱。'
         UNION ALL SELECT '我想把你藏起来，藏在只有我知道的温柔里。'
         UNION ALL SELECT '你要是愿意，我就永远爱你；你要不愿意，我就永远相思。'
         UNION ALL SELECT '今天也想见你，不管什么天气。'
         UNION ALL SELECT '我不是一个温柔的人，但是为了你，我愿意做尽温柔的事。'
         UNION ALL SELECT '我这一生最美好的场景，就是遇见你。'
         UNION ALL SELECT '你的眼睛真好看，里面有日月冬夏，晴雨山川，还有我。'
         UNION ALL SELECT '山野千里，你是我藏在星星里的浪漫。'
         UNION ALL SELECT '我想和你一起看日出到日落，从春夏到秋冬。'
         UNION ALL SELECT '你是我疲惫生活里唯一的英雄梦想。'
         UNION ALL SELECT '我的择偶标准很简单，第一是你，第二还是你。'
         UNION ALL SELECT '你不用刻意改变，因为你本来的样子我就很喜欢。'
         UNION ALL SELECT '你是我想起就会嘴角上扬的人。'
         UNION ALL SELECT '你是我所有心动和欢呼雀跃的源头。'
         UNION ALL SELECT '我喜欢你，认真且怂，从一而终。'
     ) AS seed
WHERE NOT EXISTS (SELECT 1 FROM `love_words` LIMIT 1);
